### ISSUE TITLE
Template literal error on line 4 github.js

### ISSUE THREAD

**Issue by bobbysebolao** [oliverjam/learn-promises#2]
For some reason the template literal on line 4 causes an error when I run this file (github.js):

```
const getUser = username => {
  return request(`https://api.github.com/users/{username}`);
};
```

But when I change it to a string + variable concatenation, it runs just fine:

```
const getUser = username => {
  return request("https://api.github.com/users/" + username);
};
```

I'm not sure why this is happening! I wonder, do you get the same error? I was thinking that it could be to do with my version of VS Code (I'm due an update).

**Comment by oliverjam** [comment]
I'm confused: are you talking about `solution/github.js`? My `getUser` is on line 7, and looks like this:

```js
const getUser = username => request(`https://api.github.com/users/${username}`);
```

Your version is missing a `$` before the interpolation—where are you seeing this function?

**Comment by bobbysebolao** [comment]
Oh yes! That was the issue, I was missing the dollar sign 😅 this is a non issue...

**Comment by oliverjam** [comment]
Ahh that was code you wrote? I guess you copied the URL from the README? I was trying to signify that as a placeholder value, but maybe it looks too similar to a template string. I could use double curlies to make it more obvious

**Comment by bobbysebolao** [comment]
AH, that was it! I copied the code from the readme, there is a typo in the readme (not a typo, but you know what I mean :) )

**Comment by oliverjam** [comment]
Sorry it's not a typo, the `{username}` was intended to communicate that this is a value that needs to be replaced in the url. It would be more clear to do something like `"https://api.github.com/users/{{USERNAME_GOES_HERE}}"`

**Comment by bobbysebolao** [comment]
Yep, I misread it the first time, that makes perfect sense! Feel free to close this issue.
